site_name: Physical Computing Resources
site_url: https://gersteinj-middlesex.github.io/circuitpython-resources/
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Troubleshooting: troubleshooting.md
  - Development Environment: ide.md
  - Links: more-resources.md
  - Quick Reference:
    - Data Types and Variables: quickref\data-and-variables.md
    - Control Structures: quickref\control-structures.md
  - Exercises:
    - 001 - Printing: exercises\001-printing.md
    - 002 - Imports: exercises\002-imports.md
    - 003 - DigitalIO: exercises\003-digitalio.md
    - 004 - Blink Pattern: exercises\004-blink-pattern.md
    - 005 - Addressable LED: exercises\005-addressable-rgb.md
    - 006 - Working with Colors: exercises\006-colors.md
    - 007 - Stepping Between Values: exercises\007-stepping-between-values.md
    - 008 - Digital Inputs: exercises\008-digital-inputs.md
    - 009 - Conditional Statements: exercises\009-conditional-statements.md
    - 010 - More Conditional Statements: exercises\010-more-conditionals.md
theme:
  name: material
  palette:
    scheme: slate
    primary: cyan
    accent: deep purple
  features:
    - content.code.annotate
markdown_extensions:
  - admonition
  - pymdownx.keys
  - abbr
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
  # - pymdownx.inlinehilite
  - pymdownx.superfences 
  - toc