site_name: Physical Computing Resources
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Troubleshooting: board.md
  - Development Environment: ide.md
  - Links: more-resources.md
  - Quick Reference:
    - Data Types and Variables: quickref\data-and-variables
    - Control Structures: quickref\control-structures
  - Exercises:
    - 001 - Printing: exercises\001-printing.md
    - 002 - Imports: exercises\002-imports.md
    - 003 - DigitalIO: exercises\003-digitalio.md
    - 004 - Blink Pattern: exercises\004-blink-pattern.md
theme:
  name: material
  palette:
    scheme: slate
    primary: cyan
    accent: deep purple
markdown_extensions:
  - admonition
  - pymdownx.keys
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - abbr
  - pymdownx.snippets
  # - attr_list
  - def_list
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
  # - pymdownx.inlinehilite
  - pymdownx.superfences 
  - toc