site_name: CircuitPython Resources
nav:
  - Home: index.md
  - Board: board.md
  - IDE: ide.md
theme:
  name: material
  palette:
    scheme: slate
    primary: cyan
    accent: deep purple
markdown_extensions:
  - admonition
  - pymdownx.keys
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - abbr
  - pymdownx.snippets
  # - attr_list
  - def_list